# Generated by Django 6.0 on 2025-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markazlar',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='markazlar_images/'),
        ),
    ]
